### ISSUE TITLE
Grunt: legacssy and autoprefixer

### ISSUE THREAD

**Issue by danny8000** [cfpb/design-manual#27]
I need to figure out if we need to use legacssy and autoprefixer. These are commonly used in the captial framework grunt files.

**Comment by himedlooff** [comment]
I would highly recommend using autoprefixer because it adds in vendor prefixes for you.

> Write your CSS rules without vendor prefixes (in fact, forget about them entirely):
> 
> ``` CSS
> :fullscreen a {
>     transition: transform 1s
> }
> ```
> 
> Process your CSS by Autoprefixer:
> 
> ``` JS
> var prefixed = autoprefixer.process(css).css;
> ```
> 
> It will use the data on current browser popularity and properties support to apply prefixes for you:
> 
> ``` CSS
> :-webkit-full-screen a {
>     -webkit-transition: -webkit-transform 1s;
>     transition: transform 1s
> }
> :-moz-full-screen a {
>     transition: transform 1s
> }
> :-ms-fullscreen a {
>     transition: transform 1s
> }
> :fullscreen a {
>     -webkit-transition: -webkit-transform 1s;
>     transition: transform 1s
> }
> ```

https://github.com/ai/autoprefixer

**Comment by himedlooff** [comment]
Use legacssy if we want to support older IE versions that do not support media queries. It will create a separate stylesheet that strips out media queries. For example it would turn this...

``` CSS
body {
  margin: 0;
  padding: 0;
}

@media only screen and (min-width: 768px) {
  h1 {
    font-weight: bold;
  }
}
```

into this...

``` CSS
body {
  margin: 0;
  padding: 0;
}

h1 {
  font-weight: bold;
}
```

http://robin.medvedi.eu/mobile-first-and-ie8-solution-introducing-grunt-legacssy/
